### ISSUE TITLE
Can't settle as arbiter until 256 blocks pass

### ISSUE THREAD

**Issue by myhndl** [polyswarm/contracts#1]
This makes me think that there is getWeightedRandomArbiter causing it to fail.
Getting the dreaded out of gas or always failing transaction error message

**Comment by Rizato** [comment]
Crashes here

```
626:         return int256(uint256(keccak256(abi.encodePacked(blockhash(targetBlock), seed))) % range);
```

**Comment by ceseale** [comment]
@Rizato did increasing the stake solve this?

**Comment by Rizato** [comment]
Yep. It was an extra indent screwed up my staking transaction. All good & was an arbiter issue all along.
