### ISSUE TITLE
approveWithdrawal allows withdrawals of 0 NCT

### ISSUE THREAD

**Issue by supernothing** [polyswarm/contracts#120]
**Describe the bug**
[`approveWithdrawal` allows the "withdrawal" of 0 NCT](https://github.com/polyswarm/contracts/blob/16d0c9398911dd33dc0bb23d4a1641427217b738/contracts/ERC20Relay.sol#L169), which could be used to very cheaply DoS the verifiers by exhausting their ETH balance. Additionally, [the check before transferring to the recipient](https://github.com/polyswarm/contracts/blob/16d0c9398911dd33dc0bb23d4a1641427217b738/contracts/ERC20Relay.sol#L210) should be of `net` not `amount`.

**Expected behavior**
It's not trivial for a malicious participant to exhaust verifier ETH. I think the proper fix here is to set a minimum fee, and ensure that the amount is greater than the fee. Also, obviously, checking net rather than amount when transferring to the recipient.

**Comment by mjkoo** [comment]
Should be resolved in #122
