### ISSUE TITLE
removeVerifier incorrectly re-orders verifiers list

### ISSUE THREAD

**Issue by supernothing** [polyswarm/contracts#121]
**Describe the bug**
[The way verifiers are deleted in `removeVerifier`](https://github.com/polyswarm/contracts/blob/16d0c9398911dd33dc0bb23d4a1641427217b738/contracts/ERC20Relay.sol#L117) can cause other verifiers to lose their status, as `verifierAddressToIndex` will no longer contain the correct index mappings. For instance, if we have verifiers [A, B, C] and B is deleted, C's index becomes 1 but this is not updated in the appropriate mapping, causing `isVerifier` to potentially return `false` for C.

**Expected behavior**
Calling `removeVerifier` only removes the intended verifier, and properly updates the index mapping.

**Comment by mjkoo** [comment]
Should be resolved in #122
