### ISSUE TITLE
Offers: Cancel event

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/contracts#35]
Seems that if an ambassador opens an offer then cancels, expert will receive "open" event but subsequent join will fail and expert won't be notified.

Related: "Cancel" and "Closed" event names seem to be somewhat inconsistent in e.g. polyswarmd

**Comment by ceseale** [comment]
Got added here `Cancel Event` added here https://github.com/polyswarm/contracts/blob/master/contracts/OfferMultiSig.sol#L133
