### ISSUE TITLE
Fund testing addresses with NCT only on sidechain

### ISSUE THREAD

**Issue by ceseale** [polyswarm/contracts#38]
**Is your feature request related to a problem? Please describe.**
As a part of testing relay the contract config needs to fund the micro engine accounts only on sidechain. This should only be implemented once relay is added to e2e. 

**Describe the solution you'd like**
create_config.js should mint NCT only on sidechain

**Comment by myhndl** [comment]
Blocks on https://github.com/polyswarm/relay/issues/2

**Comment by Rizato** [comment]
https://github.com/polyswarm/contracts/pull/72

I went the other way with that. I mint only on homechain, expecting NCT to be relay'd to the sidechain.
