### ISSUE TITLE
--idempotent flag no longer works, migrations still ran

### ISSUE THREAD

**Issue by scsich** [polyswarm/contracts#39]
**Describe the bug**
`--idempotent` is meant to keep migrations from running again if contract already exist in network. this is not considered failure and should exit 0. Currently, the check is run in bash:

```

if [[ $1 == "--idempotent" && -f "build/polyswarmd.yml" ]]; then
    >&2 echo "polyswarmd.yml detected in idempotent mode, exiting"
    exit
fi

... then we go on to migrate + create config in consul
```

Since create_config.js no longer dumps a yaml, it writes to consul, `build/polyswarmd.yml` is never written.. Furthermore, create_config.js does't check if there is an existing config for this sidechain up in consul. 

**To Reproduce**
1. Re-run contracts in staging `docker service update --force gamma_contracts`
2. Observe failure in migrations, even though idempotent flag should obviate pushing contracts

**Expected behavior**
Idempotent flag means that consul is consulted first, if existing contracts/configuration for sidechain: bail.

**Comment by scsich** [comment]
@ceseale can you please fix this, I just ran into today and it borked staging.

**Comment by scsich** [comment]
@ceseale please pickup with some cleanup stuff, I fixed the immediate issue here:

https://github.com/polyswarm/contracts/tree/fix/check-consul-before-overwrite

But a few things still happen:

1. Truffle migration will still run on container restart even if consul key is there (migrate_and_create_config.sh).
1. Contracts wait for gas limit but you probably want to to other checks relevant to having 3 sealers:
* Are blocks advancing
* Accounts on both home and side unlocked?

**Comment by ceseale** [comment]
@scsich awesome, will do.

**Comment by ceseale** [comment]
Forgot to update this earlier, should be fixed now with https://github.com/polyswarm/contracts/pull/41 and https://github.com/polyswarm/contracts/pull/44
