### ISSUE TITLE
Various Issues with Contract Deployment Error Conditions

### ISSUE THREAD

**Issue by scsich** [polyswarm/contracts#43]
**Describe the bug**

Several errors in `migrate_and_create_config.sh` prevent clean deployment in new environment when Consul is in a clean state.

**To Reproduce**

1. Deploy contracts without /chain/sidechain_name key existing
2. `migrate_and_create_config.sh` claims ABI already exist because of `curl` error (404), it does not.

```
gamma_contracts.1.hzt0mgk0nbse@ip-172-31-58-151    |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
gamma_contracts.1.hzt0mgk0nbse@ip-172-31-58-151    |                                  Dload  Upload   Total   Spent    Left  Speed
100    40  100    40    0     0   1176      0 --:--:-- --:--:-- --:--:--  1176
gamma_contracts.1.hzt0mgk0nbse@ip-172-31-58-151    | ABIs already exist, skipping contract migration
```

3. Script continues thinking contracts are in local file system, they because ABI exists in Consul. This will not work if we remove volume backing from contracts container. 

```
gamma_contracts.1.ptzvg81rihdb@ip-172-31-58-151    | Error: ENOENT: no such file or directory, scandir '/build/contracts'
```
Also, the check abi function doesn't take a parameter and only ever looks at NectarToken contract:

`curl --header $header -silent "$CONSUL/v1/kv/chain/$POLY_SIDECHAIN_NAME/NectarToken" | grep -vq Value` 

If curl fails, you never get to `grep`'s return code.

https://github.com/polyswarm/contracts/blob/master/scripts/migrate_and_create_config.sh#L40

**Expected behavior**
Move this out of bash into JS or some other language where you can do the following:

* Check if you're 200'ing on looking for Consul keys, everything else means problem  (500) or ABI not exist (404)
* Don't bail if you get a 404
* Bail if you get something from Consul in the 500 series and report Consul broken
* Don't assume `/build/contracts` exists if you get a 404 from consul

My suggestion would be to use a ready-made consul library because you will get better error/exception handling in a language that isn't bash.

**Comment by scsich** [comment]
@ceseale when can I expect you to begin a rewrite here and fix these issues?

**Comment by ceseale** [comment]
@scsich starting now
