### ISSUE TITLE
Array members of bounties not included in lookups

### ISSUE THREAD

**Issue by myhndl** [polyswarm/contracts#5]
Limitation of the solidity ABI I believe, new experimental ABI encoder might be able to fix but need to research the compatibility implications of turning it on.

**Comment by myhndl** [comment]
@ceseale do you have an idea what this ticket was about?

**Comment by ceseale** [comment]
I think this is about us not being about to return array members of the bounty [struct](https://github.com/polyswarm/contracts/blob/master/contracts/BountyRegistry.sol#L28-L30).

**Comment by Rizato** [comment]
I bet these are the same issue https://github.com/polyswarm/contracts/issues/51
