### ISSUE TITLE
Arrays in the Bounty struct are not accessible outside the contract

### ISSUE THREAD

**Issue by Rizato** [polyswarm/contracts#51]
**Describe the bug**
the bountiesByGuid mapping should relate guid to Bounty struct in the contract.
However, when looking at the compiled abi, several of the fields are missing from the outputs array.
That means, clients cannot access that information.

The missing fields are all array values.

**To Reproduce**
1. truffle compile
2. Open `build/contracts/BountyRegistry.json`
3. Scroll down to `bountiesByGuid`
4. Look at outputs

**Expected behavior**
All the fields in struct should be listed as an output

**Additional context**
https://github.com/polyswarm/contracts/blob/master/contracts/BountyRegistry.sol#L16

**Comment by Rizato** [comment]
Studying the issue and brainstorming alternatives

**Comment by Rizato** [comment]
Writing the changes now. 
Going with a system where all arrays are now accessible with a typeByGuid mapping.

Running into issues with quroumVerdictsByGuid. 
That was originally a `mapping (uint256 => uint256)` and now it needs to be a `mapping (uint128 => mapping (uin256 => uint256))`. 
However, doing that makes it harder to manipulate.
Need to see how something like that is done.

**Comment by Rizato** [comment]
Got superceded by consumer & autopsy module. Back in action on this.

**Comment by myhndl** [comment]
@Rizato whats the status here

**Comment by Rizato** [comment]
@myhndl Same as before. I have not implemented
