### ISSUE TITLE
Migration can Hang Forever

### ISSUE THREAD

**Issue by scsich** [polyswarm/contracts#53]
**Describe the bug**
A migration failed in `staging` and contracts just hung forever. This prevents restarting the contracts container and re-attempting migration when `geth` came backup.

**To Reproduce**
1. Start migration with less than 3x sealers
2. Watch it hang
3. Restart geth instances
4. Still watch it hang

**Expected behavior**
Contract container should die if migration hangs more more than some configurable amount of time, say 5 mins.

**Comment by ceseale** [comment]
Should have closed with #54
