### ISSUE TITLE
Unit tests and lints in CI

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/contracts#57]
**Is your feature request related to a problem? Please describe.**
CI config currently kicks integration tests, it should also 
1) Run unit tests and fail if they don't pass
2) Check code with solium (Not currently solium clean, upcoming PR will resolve)

**Describe the solution you'd like**
Add both these steps to .gitlab-ci.yml

**Comment by ceseale** [comment]
Keep in mind some the tests aren't compatible with geth because they use the `evm_mine` method to accelerate blocks which is only available via test-rpc/ganache.
