### ISSUE TITLE
Inline OfferLib

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/contracts#58]
**Describe the bug**
OfferRegistry calls OfferLib via delegatecall in several places, this seems unnecessary and delegatecall is error-prone, to me it seems like this could be reasonably inlined into OfferRegistry. Given our contract deployment story currently this would be preferable, willing to hear any potential downsides @ceseale

**Comment by myhndl** [comment]
Applying blocker as this involves code changes to contracts, which blocks security analysis.
