### ISSUE TITLE
Add Guards to withdraw() in ArbiterStaking Contract

### ISSUE THREAD

**Issue by myhndl** [polyswarm/contracts#6]
withdraw() in ArbiterStaking is a fairly complex security-critical function. While I haven't seen anything obviously vulnerable, I think it would be preferable if both receiveApproval and withdraw checked to make sure the caller is an arbiter, since these are the only accounts that should be using it anyway. This could cause problems if an arbiter loses status I guess while staking, but I thought that was the point of staking? Additionally, I worry that receiveApproval is easy to DoS by spamming deposits with 1/1016 NCT, especially with gas cost concerns discussed later.

**Comment by Rizato** [comment]
Holding off on this. Adding this would effectively result in confiscating NCT from arbiters we remove.

**Comment by Rizato** [comment]
Closing for now. If we want to implement this, we should have a wider discussion on confiscating arbiter NCT. (Including what happens, and a way to remove it from lockup. Right now, the only way would be to add all arbiters back after we switch contracts so they could remove)
