### ISSUE TITLE
ERC20Relay contract seems to always have bytecode diff during contract deployment

### ISSUE THREAD

**Issue by ceseale** [polyswarm/contracts#67]
**Describe the bug**
For some reason the ERC20Relay contract's byte code is different during deploys and is causing all the contracts to redeploy when they haven't changed.

**To Reproduce**
1. Do a force update on staging with no changes to the contract src
2. Notice the logs say there is a difference is byte code for ERC20Relay

**Expected behavior**
It should only redeploy if there is a difference in the contract source

**Comment by myhndl** [comment]
Moving to Smart Contracts column

**Comment by ceseale** [comment]
The issue is the place holder address for ERC20Relay is the zero address since it's not [deployed](https://github.com/polyswarm/contracts/blob/master/scripts/create_config.js#L155) there's always a difference between bytecodes so, this should resolve once they get deployed via options.

**Comment by ceseale** [comment]
Going to keep this open until I can verify.

**Comment by ceseale** [comment]
Okay, fix verified in staging deploying going to close.
