### ISSUE TITLE
Deploy logic duplicated between migrations and create_config.js

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/contracts#83]
**Is your feature request related to a problem? Please describe.**
Unclear what is the actual deploy process (it's create_config.js for all intents and purposes except the truffle test suite), deduplicate this.

**Comment by ceseale** [comment]
Going to try leaving the actual deploying part to truffle's migration so it's less confusing. `create_config.js` will probably have to change to creating a config for one chain at a time instead of doing both.

**Comment by mjkoo** [comment]
Irrelevant due to contractor
