### ISSUE TITLE
Unless contract owner set in config, sidechain will use homechain first account

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/contracts#86]
**Describe the bug**
If `{homechain|sidechain}_contracts_owner` is not set, `deployTo` uses `web3.eth.accounts[0]` but `web3` provider isn't updated to point to the correct chain, leading to an incorrect deployment address.

**To Reproduce**
1. Deploy on homechain and sidechain with config not set and different eth.account[0]'s
2. Experience existential sadness

**Expected behavior**
Ideally we can get the account from the correct client as a sane fallback.

**Comment by mrtizmoatwork** [comment]
@mjkoo @Rizato is this still an issue?

**Comment by mjkoo** [comment]
No, irrelevant due to contractor, closing
