### ISSUE TITLE
create_config.js broken

### ISSUE THREAD

**Issue by scsich** [polyswarm/contracts#9]
In `feature/api-keys` branch of contracts repo, this script needs work. 

* File writing is asynchronous and errors do not exit code/fail the script so things continue happily
* The script has to be run twice before polyswarmd.yml pops 

Please fix this script such that it works in one shot and errors out if required functionality doesn't happen.

**Comment by mjkoo** [comment]
Resolved in https://github.com/polyswarm/contracts/commit/d3751cba9d3c6adfec67f1cf9722232d65d33508
