### ISSUE TITLE
Update to Solidity compiler to v5.0.0

### ISSUE THREAD

**Issue by ceseale** [polyswarm/contracts#98]
**Is your feature request related to a problem? Please describe.**
Some of the report slither warnings complain about old contract versions.
https://github.com/trailofbits/slither/wiki/Vulnerabilities-Description#old-versions-of-solidity
https://github.com/trailofbits/slither/wiki/Vulnerabilities-Description#constant-functions-changing-the-state

**Describe the solution you'd like**
Upgrade contract's and truffle so we get all the neat features in more recent solidity versions. This might require some refactoring as some of the changes are breaking.

**Comment by ceseale** [comment]
So, to update the compile version I have to update truffle to v5.0.0-beta.2. That has a lot of breaking changes. One of the bigger ones is Web3 has switched to bn.js over Bignumber.js. Which is messing up our testing. The fix should be as easy as switching to bn-chai but it doesn't seem to work with should.js https://github.com/EthWorks/bn-chai/issues/2.

@myhndl If upgrading isn't a blocker, I'm going to hold off on this. Otherwise I can work around bn-chai.

**Comment by myhndl** [comment]
Upgrading is not a blocker for today, but let's get this done next week.

**Comment by ceseale** [comment]
Waiting on https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1568 to update truffle and our contracts solc versions. Otherwise zeppelin contracts won't compile with truffle v5.

**Comment by ceseale** [comment]
See PR #133
